[package]
name = "ray"
version = "0.1.0"
authors = ["Joseph Ryan <josephryan3.14@gmail.com>"]
edition = "2018"

[lib]
name = "ray"
path = "src/lib.rs"

[dependencies]
image = "0.21.0"
itertools = "0.8.0"
rand = "0.6.3"
rayon = "1.0.3"
termion = "1.5.1"

[profile.release]
debug = true
